# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PostcardRecord' do
  pod 'AVOSCloud' 
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PostcardRecord

  target 'PostcardRecordTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PostcardRecordUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
