//
//  Header_Image.h
//  AnXin
//
//  Created by xxb on 2018/1/18.
//  Copyright © 2018年 xxb. All rights reserved.
//

#ifndef Header_Image_h
#define Header_Image_h


/*************图片名*************/
#define XBImageName_bannerPlaceHolderImg            @"banner"



/*************图片*************/
#define XBImage_团餐预定默认                          UIImageName(@"团餐预定默认")
#define XBImage_团餐预定按下                          UIImageName(@"团餐预定按下")
#define XBImage_养生食疗默认                          UIImageName(@"养生食疗默认")
#define XBImage_养生食疗按下                          UIImageName(@"养生食疗按下")
#define XBImage_消息默认                              UIImageName(@"消息默认")
#define XBImage_消息按下                              UIImageName(@"消息按下")
#define XBImage_菜主图片                              UIImageName(@"菜主图片")
#define XBImage_晚                                   UIImageName(@"晚")
#define XBImage_午                                   UIImageName(@"午")
#define XBImage_返回默认                              UIImageName(@"返回默认")
#define XBImage_返回按下                              UIImageName(@"返回按下")
#define XBImage_下拉箭头默认                           UIImageName(@"下拉箭头默认")
#define XBImage_下拉箭头按下                           UIImageName(@"下拉箭头按下")
#define XBImage_搜索白色默认                           UIImageName(@"搜索白色默认")
#define XBImage_搜索白色按下                           UIImageName(@"搜索白色按下")
#define XBImage_无内容                                UIImageName(@"无内容")
#define XBImage_未选中按下                             UIImageName(@"未选中按下")
#define XBImage_选中默认                               UIImageName(@"选中默认")
#define XBImage_重新定位默认                            UIImageName(@"重新定位默认")
#define XBImage_地址                                  UIImageName(@"地址")
#define XBImage_微信                                  UIImageName(@"微信")
#define XBImage_QQ                                   UIImageName(@"QQ")
#define XBImage_关闭白色按下                           UIImageName(@"关闭白色按下")
#define XBImage_关闭白色默认                           UIImageName(@"关闭白色默认")
#define XBImage_关闭白色默认                           UIImageName(@"关闭白色默认")
#define XBImage_top背景四寸                             UIImageName(@"top背景4")
#define XBImage_top背景四点七寸                          UIImageName(@"top背景47")
#define XBImage_top背景五点五寸                          UIImageName(@"top背景55")
#define XBImage_top背景五点八寸                          UIImageName(@"top背景58")
#define XBImage_tabbar阴影四寸                          UIImageName(@"底部投影4")
#define XBImage_tabbar阴影四点七寸                      UIImageName(@"底部投影47")
#define XBImage_tabbar阴影五点五寸                      UIImageName(@"底部投影55")
#define XBImage_tabbar阴影五点八寸                      UIImageName(@"底部投影X")
#define XBImage_手机                                    UIImageName(@"手机")
#define XBImage_验证码                                 UIImageName(@"验证码")
#define XBImage_设置默认                                 UIImageName(@"设置默认")
#define XBImage_设置按下                                 UIImageName(@"设置按下")
#define XBImage_添加默认                                 UIImageName(@"添加默认")
#define XBImage_添加按下                                 UIImageName(@"添加按下")
#define XBImage_购物车                                 UIImageName(@"购物车")
#define XBImage_购物车空                                 UIImageName(@"购物车空")
#define XBImage_删除按下                                 UIImageName(@"删除按下")
#define XBImage_删除默认                                 UIImageName(@"删除默认")
#define XBImage_增加默认                                 UIImageName(@"增加默认")
#define XBImage_增加按下                                 UIImageName(@"增加按下")
#define XBImage_减少默认                                 UIImageName(@"减少默认")
#define XBImage_减少按下                                 UIImageName(@"减少按下")
#define XBImage_搜索浅灰                                 UIImageName(@"搜索浅灰")
#define XBImage_我的钱包默认                              UIImageName(@"我的钱包默认")
#define XBImage_我的钱包按下                              UIImageName(@"我的钱包按下")
#define XBImage_地址默认                                 UIImageName(@"地址默认")
#define XBImage_地址按下                                 UIImageName(@"地址按下")
#define XBImage_邀请默认                                 UIImageName(@"邀请默认")
#define XBImage_邀请按下                                 UIImageName(@"邀请按下")
#define XBImage_联系我们默认                              UIImageName(@"联系我们默认")
#define XBImage_联系我们按下                              UIImageName(@"联系我们按下")
#define XBImage_进入默认                                  UIImageName(@"进入默认")
#define XBImage_进入按下                                 UIImageName(@"进入按下")
#define XBImage_待付款默认                                  UIImageName(@"待付款默认")
#define XBImage_待付款按下                                 UIImageName(@"待付款按下")
#define XBImage_已付款默认                                  UIImageName(@"已付款默认")
#define XBImage_已付款按下                                 UIImageName(@"已付款按下")
#define XBImage_已完成默认                                  UIImageName(@"已完成默认")
#define XBImage_已完成按下                                 UIImageName(@"已完成按下")
#define XBImage_取消默认                                  UIImageName(@"取消默认")
#define XBImage_取消按下                                  UIImageName(@"取消按下")
#define XBImage_食                                       UIImageName(@"食")
#define XBImage_团                                       UIImageName(@"团")
#define XBImage_未选中默认                                UIImageName(@"未选中默认")
#define XBImage_关闭默认                                  UIImageName(@"关闭默认")
#define XBImage_关闭按下                                  UIImageName(@"关闭按下")
#define XBImage_转发默认                                  UIImageName(@"转发默认")
#define XBImage_转发按下                                  UIImageName(@"转发按下")
#define XBImage_微信支付                                  UIImageName(@"微信支付")
#define XBImage_支付宝                                    UIImageName(@"支付宝")
#define XBImage_重新定位按下                               UIImageName(@"重新定位按下")
#define XBImage_头像默认                                  UIImageName(@"头像默认")
#define XBImage_头像默认群                                  UIImageName(@"头像默认_群")
#define XBImage_定位当前位置                                  UIImageName(@"定位当前位置")
#define XBImage_tip成功                                     UIImageName(@"tip-成功")
#define XBImage_tip繁忙                                     UIImageName(@"tip-繁忙")
#define XBImage_tip加载                                     UIImageName(@"tip-加载")
#define XBImage_tip警示                                     UIImageName(@"tip-警示")
#define XBImage_tip失败                                     UIImageName(@"tip-失败")
#define XBImage_更新通知                                     UIImageName(@"更新通知")
#define XBImage_订单通知                                     UIImageName(@"xxxx订单")
#define XBImage_活动通知                                     UIImageName(@"xxxx活动")
#define XBImage_展开默认                                     UIImageName(@"展开默认")
#define XBImage_收起默认                                     UIImageName(@"收起默认")
#define XBImage_余额支付                                     UIImageName(@"余额支付")
#define XBImage_播放按钮                                     UIImageName(@"播放按钮")
#define XBImage_logo                                        UIImageName(@"logo")
#define XBImage_inviteLogo                                  UIImageName(@"inviteLogo")



#endif /* Header_Image_h */
